name: focusFlow CI/CD (Self-Hosted)

on:
  workflow_dispatch: # Manual trigger

jobs:
  build-and-push:
    runs-on: self-hosted # Use a self-hosted runner where the .env file is already present

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Copy pre-existing .env file
      run: |
        # Copy your .env file from a secure location on the runner
        # Adjust the path based on where you store your .env file on your self-hosted runner
        cp ~/.focusflow-secrets/.env .env
        echo "Copied .env file from secure location on the runner"

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: docker/Dockerfile # Point to actual Dockerfile
        push: true
        tags: mubaraklouis/focusflow:1.1.2
        build-args: |
          WWWGROUP=1000
          WWWUSER=1000
